language: python

python:
  - 2.6
  - 2.7

before_install:
 - sudo apt-get install texlive-full

install:
  - "pip install -r requirements.txt --use-mirrors"

script:
  - make html && make html
  - make singlehtml && make singlehtml
  - make text
  - make singletext
  - make latexpdf
